### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by leonhardhennig** [DFKI-NLP/sherlock#30]
- current Transformers version
- compatible AllenNLP version (same as in RelEx repo!)

and test, e.g. if issue #29  works

when done, merge into branch [sherlock_version_2](https://github.com/DFKI-NLP/sherlock/tree/sherlock_version_2)

**Comment by GabrielKP** [comment]
It seems like the new tokenizer from huggingface are not compatible with python 3.9.7 - but work with python 3.8.

**Comment by GabrielKP** [comment]
After minor adaptations the repository works good in python 3.8:

- Relation classification:
```
f1 = 0.7062233068944478
precision = 0.7164964407304241
recall = 0.6962406015037594
```

- Named Entitiy Recognition
```
f1 = 0.8298232372419166
loss = 0.21359181425055318
precision = 0.8428022107098257
recall = 0.8172379479432675
```
