### ISSUE TITLE
AllenNLP support

### ISSUE THREAD

**Issue by ChristophAlt** [DFKI-NLP/sherlock#8]
This is dependent on #5.
- After introducing the Annotator concept, add an AllenNLPAnnotator that loads an AllenNLP model archive.
- AllenNLPAnnotator can then be subclassed to add arbitrary models, e.g. from RelEx.

**Comment by GabrielKP** [comment]
Some confusions I gathered along the way:
- allenNLP works with these config files, but there is also the python interface: which to prioritize? (optimally both) (see solution below)
- in sherlock the concept "DatasetReader" already exists, but the same concept exists in allenNLP too - this causes a name-clash.

- This seems to be the best solution to approach this issue:
     1. Make allennlp models work and trainable via the old DatasetReader + FeaturerConverter mechanic
     2. Implement an allennlp-specific DatasetReader using implementation in number 1
     3. This would allow for any additional DatasetReader for Sherlock automatically work with Allennlp without adaption
     4. This still would not prevent a name clash
     5. This is dependent on the solution of #36 

Thus the main task would be to solve #36 and then implement an allennlp feature converter.
Tagging @leonhardhennig

**Comment by GabrielKP** [comment]
Discussed approach:
- In the AllenNLP Annotator, convert InputFeatures into AllenNLP format
- In the FeatureConverter:
    - Remove the Tokenizer away from Signature
    - create new class FeatureConverterTransformer, FeatureConverterAllenNLP
    - reimplement binary_rc for allennlp

Optimally, the featureconverter would not have its own implementation for allennlp and transformers, but at the moment this seems to be the best solution.

**Comment by GabrielKP** [comment]
New Idea:

Instead of creating a new FeatureConverter for allennlp and transformers every time, give a parameter "framework".
FeatureConverter then implements a function which depending on "framework" chooses to do its last conversion to InputFeatures for allennlp or transformers. This would allow featureconverters to share most of their code between frameworks whilst still allowing for flexibility in only implementing one framework.

**Comment by GabrielKP** [comment]
It finally is done.

You can train models from the root-folder with `allennlp train path/to/config -s path/to/serialization_dir`.
These then can be evaluated either with:
1. `scripts/eval_binary_relation_clf_allennlp.py --output_dir path/to/serialization_dir --eval_data_path path/to/eval_data --test_data_path path/to/test_data --do_eval --do_predict --eval_all_checkpoints`
2. `allennlp evaluate path/to/serialization_dir path/to/eval_data`

These models also can be loaded into the Annotator, but this has not been tested in action yet.

2 example configs are included:
* [bert](configs/binary_rc/transformer.jsonnet)
* [cnn](configs/binary_rc/cnn.jsonnet)

The first option mirrors the outputs of the original `run_relation_clf.py` script for the flags `--do_predict` and `--do_eval`.
